print("\nOnline Store")
print("------------------------")
print("Product(s)                Price")
print("Item 1                    ", float(11))
print("Item 2                    ", float(12))
print("Item 3                    ", float(13))
print("Combo 1 (Item 1 + 2)      ", float())
print("Combo 2 (Item 2 + 3)      ", float(22))
print("Combo 3 (Item 1 + 3)      ", float(23))
print("Combo 4 (Item 1 + 2 + 3)  ", float(24))
print("------------------------")
print("For delivery Contact: 98764678899")
